batch_size: 32
num_workers: 0
pin_memory: False

trainer:
  accelerator: "cpu"
  devices: 1

  min_epochs: 1 # prevents early stopping
  max_epochs: 10

  # mixed precision for extra speed-up
  # precision: 16

  # perform a validation loop every N training epochs
  check_val_every_n_epoch: 1

  # set True to to ensure deterministic results
  # makes training slower but gives more reproducibility than just setting seeds
  deterministic: False

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val/loss" # name of the logged metric which determines when model is improving
    mode: "min" # can be "max" or "min"
    save_top_k: 1 # save k best models (determined by above metric)
    save_last: True # additionaly always save model from last epoch
    verbose: False
    dirpath: "/tmp/checkpoints/"
    filename: "epoch_{epoch:03d}"
    auto_insert_metric_name: False
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val/loss" # name of the logged metric which determines when model is improving
    mode: "min" # can be "max" or "min"
    patience: 3 # how many epochs of not improving until training stops
    min_delta: 1e-3 # minimum change in the monitored metric needed to qualify as an improvement
